### PR TITLE
Use kubectl behaviours for `KUBECONFIG` outside the api-server and compose-controller

### PR DESCRIPTION
**Pull request by TBBle**
Apart from the API server and compose controller, the `KUBECONFIG` env-var is under the user's control, and may not be an explicit filename, but a list of files using a platform-specific separator.

So we only want to use `clientcmd.ClientConfigLoadingRules.ExplicitPath` or `clientcmd.BuildConfigFromFlags` (which uses the former) when dealing with an in-cluster service or when given an explicit `--kubeconfig` command line.

We can test this by ensuring every `KUBECONFIG` in the tests is a list of config files, including a non-existent file. This will pass using the k8s APIs for merged kubeconfig, but fails with a more naive API that tries to treat `KUBECONFIG` as a single file.

There isn't a bug report for this issue here, but it has shown up at https://github.com/docker/cli/issues/2334. https://github.com/docker/cli uses an affected API from this project (`github.com/docker/compose-on-kubernetes/api.NewKubernetesConfig`), that was not consumed or tested by any code in this repo. Part of this change uses this API in place of equivalent open-coded implementations, so we now have coverage of this API by dint of the e2e tests.

### CODE REVIEW

**Comment by TBBle** [comment]
Because sometimes they're hard to find later, [just the test change to use `KUBECONFIG` with `:`](https://app.circleci.com/pipelines/github/docker/compose-on-kubernetes/580/workflows/1de363c3-6d60-410b-97cf-b0944acc4c8d/jobs/5064) happily fails the CI run, when it hits `stat /kind-config:/nonexistant-config-file: no such file or directory`, which is the problem to be solved here.

**Comment by TBBle** [comment]
The [CI run](https://app.circleci.com/pipelines/github/docker/compose-on-kubernetes/584/workflows/0b86759b-2fb2-4199-9cd8-c422e16d012b) [for just the change to use `NewKubernetesConfig`](https://github.com/docker/compose-on-kubernetes/pull/167/commits/c33dbd566ee380531f9112fb4c760d7f353230ee) passes. In this run, the test-changes shown failing earlier were reverted.

**Comment by TBBle** [comment]
License check failures will be fixed by #170.

**Comment by chris-crone** [comment]
Hi! Thanks for your PR! Unfortunately we're no longer maintaining this repository so I will close this issue.

**Pull request closed without merging**
