### PR TITLE
remove uses of github.com/golang/glog

### PR DESCRIPTION
**Pull request by thaJeztah**
glog has the same issue as k8s.io/klog, and is calling `user.Current()`
inside an `init()`; see https://github.com/kubernetes/klog/commit/466fbb6507dbc90eba32172bb1c662640e78e0c3

Calling `user.Current()` on Windows can result in remove connections being
made to get the user's information, which can be a heavy call. See https://github.com/docker/cli/issues/2420 and https://github.com/docker/cli/pull/2515

glog was only used in a single location, so we may as well remove it.

### CODE REVIEW

**Comment by thaJeztah** [comment]
🤞 hoping vendor check passes; I manually removed the dependency from `GoDep.lock`. if I run `dep ensure` locally,  it _does_ have some changes, but it wants to add

- some symlinks in `github.com/docker/docker/integration-cli` (those are only for tests, and I know adding symlinks to git can be funky)
- adds / removes a missing newline in `vendor/github.com/coreos/etcd/Documentation/README.md`


```bash
git status -u
On branch fix_init
Your branch is up to date with 'origin/fix_init'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	vendor/github.com/coreos/etcd/Documentation/README.md
	vendor/github.com/docker/docker/integration-cli/fixtures/https/ca.pem
	vendor/github.com/docker/docker/integration-cli/fixtures/https/client-cert.pem
	vendor/github.com/docker/docker/integration-cli/fixtures/https/client-key.pem
	vendor/github.com/docker/docker/integration-cli/fixtures/https/server-cert.pem
	vendor/github.com/docker/docker/integration-cli/fixtures/https/server-key.pem

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by thaJeztah** [comment]
Looks like no version was specified for ginkgo, so it picks "latest", which expects
Go 1.16 or up.

```
Step 23/51 : RUN go get github.com/onsi/ginkgo/ginkgo
---> Running in e81e14cdf955
# github.com/onsi/ginkgo/types
../../onsi/ginkgo/types/code_location.go:30:19: undefined: os.ReadFile
../../onsi/ginkgo/types/flags.go:125:23: undefined: io.Discard
The command '/bin/sh -c go get github.com/onsi/ginkgo/ginkgo' returned a non-zero code: 2
make: *** [docker.Makefile:73: dockereng/kube-compose-controller] Error 2
```

**Review by rumpl — APPROVED** [review]
LGTM

Love to see -1506 :)

**Comment by thaJeztah** [comment]
Relates to https://github.com/docker/cli/pull/3411

**Pull request merged**
