### PR TITLE
Bump golang, alpine

### PR DESCRIPTION
**Pull request by simonferquel**
This bumps golang to version 1.12.1 and alpine to 3.9.2

### CODE REVIEW

**Comment by silvin-lubecki** [comment]
Something went wrong with the `e2e-kind` step:

```
🌟 build dockereng/kube-compose-e2e-kind-node:v-8c493e801fa231a94e7f10deb72bd4e79dffec0f
Sending build context to Docker daemon  87.39MB


Step 1/3 : ARG BASE_IMAGE=dockertesteng/kind-node:v1.13.3
Step 2/3 : FROM ${BASE_IMAGE}
manifest for dockertesteng/kind-node:v not found
docker.Makefile:71: recipe for target 'build-kind-image' failed
make: *** [build-kind-image] Error 1
Exited with code 2
```

**Comment by simonferquel** [comment]
@jcsirot I need some help here. Looks like the KUBERNETES_VERSION variable is not set for some reason in the CI

**Comment by simonferquel** [comment]
Rebased on #84

**Comment by silvin-lubecki** [comment]
This should be rebased on top of master now 🦁

**Pull request merged**
